### ISSUE TITLE
Lib is broken in gamma >=5.2 due to lacking update of hidlibrary

### ISSUE THREAD

**Issue by mhusinsky** [bj-rn/VL.Devices.SpaceMouseHID#1]
just for documentation.
nuget version 0.3.1 does not work with gamma 5.2, as the *hidlibrary* nuget it is based on has not been updated yet to support .net6, see [here](https://github.com/mikeobrien/HidLibrary/issues/134). however, in the code a [fix exists already](https://github.com/mikeobrien/HidLibrary/pull/133), it's just not in the nuget yet :(

in gamma 5.2, running the help patch of this lib throws this exception:

```
http://vvvv.org

PlatformNotSupportedException: "Operation is not supported on this platform."
    StackTrace:
        System.Action { public virtual System.IAsyncResult BeginInvoke(System.AsyncCallback callback, object object) { ... } } 
        HidLibrary.HidDeviceEventMonitor { public void Init() { ... } }  in "HidDeviceEventMonitor.cs" Ln 25
        _VL_Devices_SpaceMouseHID_.Devices.HID.SpaceMouse._Operations_+<>c__DisplayClass0_0 { internal HidLibrary.HidDevice <GetDevice>b__0() { ... } } 
        VL.Lib.Basics.Resources.ResourceProvider+<>c__DisplayClass1_0`1 { internal VL.Lib.Basics.Resources.IResourceHandle<> <New>b__0() { ... } } 
        VL.Lib.Reactive.ObservableNodes+<>c__DisplayClass12_0`2 { internal VL.Lib.Basics.Resources.IResourceHandle<> <Using>b__0() { ... } } 
        System.Reactive.Linq.ObservableImpl.Using`2+_ { public void Run(System.Reactive.Linq.ObservableImpl.Using<, > parent) { ... } }  in "Using.cs" Ln 40
        System.Runtime.ExceptionServices.ExceptionDispatchInfo { public void Throw() { ... } } 
        VL.Lang.Platforms.RuntimeHost { private void SharedStep() { ... } } 

```

**Comment by bj-rn** [comment]
You can use the SpaceMusic fork for now. Tebjan added the HidLibrary dll for exactly that reason.

https://github.com/SpaceMusicZH/VL.Devices.SpaceMouseHID/tree/master

**Comment by bj-rn** [comment]
This should be fixed now. It is using an [unofficial nuget package](https://www.nuget.org/packages/HidLibrary.Unofficial) now that supports newer frameworks.
